<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Contracts.Common" />
    <PackageReference Include="LanguageCardsBot.Contracts.Messaging" />
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="NSwag.MSBuild" PrivateAssets="All" />
    <PackageReference Include="RabbitMQ.Client" />
    <ProjectReference Include="..\Cards.Application\Cards.Application.csproj" />
    <ProjectReference Include="..\Cards.Domain\Cards.Domain.csproj" />
  </ItemGroup>

  <Target Name="GeneratePassportClient">
    <MakeDir Directories="$(MSBuildProjectDirectory)/Passport/Generated" />
    <Exec Command="$(NSwagExe_Net100) run Passport/nswag.json"
          WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>
</Project>