<Project>
  <PropertyGroup>
    <PassportOpenApiSpec Condition="'$(PassportOpenApiSpec)' == ''">$(MSBuildThisFileDirectory)..\openapi\passport-auth-v1.yaml</PassportOpenApiSpec>
    <PassportInternalOpenApiSpec Condition="'$(PassportInternalOpenApiSpec)' == ''">$(MSBuildThisFileDirectory)..\openapi\passport-internal-v1.yaml</PassportInternalOpenApiSpec>
  </PropertyGroup>
</Project>
